### ISSUE TITLE
To Do list for 25th September - 29th September

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#107]
## DBHub.io

* [x] Initial implementation of Merge Requests dc63f98c0ce2742bd7bae8fe047ad2058107564d
* [x] Fix the expired cert problem on the DB4S end point
  * Server cert had expired.  New one installed now. :smile:
## DB4S

* [ ] Look into the OSX stuttering problem: https://github.com/sqlitebrowser/sqlitebrowser/issues/1134 - **\*in progress\***
  * [x] Try out the [3rd May nightly build](https://nightlies.sqlitebrowser.org/osx/2017-05/DB%20Browser%20for%20SQLite-sqlcipher_20170503.dmg) - just prior to the QScintilla update - to see if the problem is present in that
  * The problem does seem to arrive with our update to QScintilla 2.10.0.  Tried a few potential source changes to see if a smoking gun could be found, but nothing so far. 😦 
* [x] File bug report for Qt `QImageReader::canRead()`, as it's incorrectly returning `true` for any string starting with "BMS": https://github.com/sqlitebrowser/sqlitebrowser/issues/1138
  * https://bugreports.qt.io/browse/QTBUG-63515
* [x] Check if the CSV preview problem here still happens: https://github.com/sqlitebrowser/sqlitebrowser/issues/720

**Comment by justinclift** [comment]
Incomplete items moved to #109
