### ISSUE TITLE
To Do list for 2nd October - 6th October

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#109]
## DBHub.io

* [x] Clean up display of the Merge Request creation page
* [ ] Include branch name in JSON listings #108 9caf4346c2e9174067b5be66ad41eaacc09b86c1 - **\* in progress \***
* [x] Look into the server side part of https://github.com/sqlitebrowser/sqlitebrowser/issues/1136 7bbfa760221e21ed6f66d82d7e602bdbfb5fe4f9
  * The invalid info was being caught correctly, but the returned http status code was 500 ("Internal server error") instead of 400 ("Bad request") for user and database name failures.  Now fixed.
* [x] Initial implementation of watchers 749541c1b4c94c65a3a99109ee4445df99b02e00
* [x] Initial implementation of status updates/notifications 3e6421dc8dc36796604f4dcaf44c85a8915ae1bb
  * Event generation, and display via webUI is working.  Sending emails still needs writing
* [x] Initial email sending of status updates 430f00539d53501574a4d4da6b8be71a2da292e8

## DB4S

* [x] File bug report for Qt `QImageReader::canRead()`, as it's incorrectly returning `true` for any string starting with the standard XML declaration (`<?xml version='1.0' encoding='utf-8'?>`): https://github.com/sqlitebrowser/sqlitebrowser/issues/1159
  * Seems very similar to [DB4S #1138](https://github.com/sqlitebrowser/sqlitebrowser/issues/1138), which was a different string triggering the same problem.
  * Filed as https://bugreports.qt.io/browse/QTBUG-63568

**Comment by justinclift** [comment]
Incomplete items moved to #111.
