### ISSUE TITLE
ToDo list items for Apr 24-28

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#31]
ToDo list for this week. :smile:

* [x] Show column headings in tables even if there are no data rows
  * Found [an example of the problem](https://dev1.dbhub.io/mkleusberg/pr921.db).  It shows up when changing to the `bbb` table using the drop down table selector.
  * Fixed with ee7a1b027b74b1b5e4ee6c9319b6381d1564c68a.
* [x] Pagination for the database table view
  * [x] Go forward and backwards one page by clicking on appropriate direction arrow(s)
  * [x] Add column widths to the data display table, so the column sizes stop jumping around with paging
  * [x] Buttons for going to the start and end of the data set rows
  * [x] Add the paginated/sorted data to memcache
* [x] Click on a column heading to sort by that heading
  * [x] Reverse the sort order by clicking a second time
* [x] Add the root directory slash "/" back to the database page breadcrumb path
  * It seems like people may not be finding the existing root directory link from the top left DBHub.io icon

Hmmm, that's actually longer than I was expecting.  Hopefully it's all doable in one week.  Lots of cut-n-paste maybe... 😁

**Comment by justinclift** [comment]
Also found a bug with memcaching vs the "MaxRows" value of logged in users.  That'll need fixing too.
