### ISSUE TITLE
ToDo list for May 1-5

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#32]
* [x] Fix the bug with memcache not correctly using the MaxRows value for logged in users
  * Fixed by fda7184b3ec6c845fbd8fe48d22c26e5d2eb050b
* [x] Implement the batch file workaround for the NSIS installer "run as Admin" problem.
  * https://github.com/sqlitebrowser/sqlitebrowser/issues/974#issuecomment-298586683
* [x] Implement PostgreSQL connection pooling. #40

**Comment by justinclift** [comment]
Ok, some of this stuff is definitely going to get pushed to next week. :wink:

**Comment by justinclift** [comment]
Moved the not-yet-completed stuff to next weeks' issue: #41
