### ISSUE TITLE
ToDo list for May 8-12

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#41]
Items for this week. :smile:

* [x] Pagination arrows aren't always showing up on dev1
  * https://dev1.dbhub.io/justinclift/Assembly%20Election%202017.sqlite
  * It happens when changing to the `Candidate_Information` table using the drop down
  * It doesn't happen when using `?table=Candidate_Information` on the URL/address bar instead
  * Fixed by 5a1d0328bb465faf8c697cf12f9a51a55862b3f1.
* [x] Update database view page so sort column, order, and row offset can be given as GET URL parameters
  * GET parameters should make it fairly easy for people to link to specific database rows for viewing
  * Done in 1751955a24f390885b632e3d25cf463f40d07ab4 & f8d9f08fb4720b0b8b773472b9d06f4ea4676d5b.
* [x] Create an initial "About us" page
  * Done in 0cdc041a26f4cabe72bba5c5c79a5a4a9c48a3b7.
* [x] Add the SHA256 value for each database to the DB4S end point database list
* [x] Add a WinXP compatible download for DB4S 3.9.1
  * Done: https://github.com/sqlitebrowser/sqlitebrowser/issues/1010

**Comment by justinclift** [comment]
Uncompleted items moved to #43
