### ISSUE TITLE
To Do list for 24th July - 28th July

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#56]
## DBHub.io

* [x] Update our internal data model
  * [x] Add input validation for all of the webUI code, so it's safe to run on the internet :wink:
    * [x] commitsPage()
    * [x] contributorsPage()
    * [x] createBranchHandler() 75b3820216f23b05624ff04081ea63a22d2508e1
    * [x] createBranchPage()
    * [x] createTagHandler() 3ae45411abdff83d690147c1b50b1803dac393b4
    * [x] createTagPage()
    * [x] deleteBranchHandler() 2de889b38407a1d2b03b18834e160cf271cebf7b
    * [x] deleteCommitHandler() 1e9215ff38deedd7b6459196c1da0afc5ee0e112
    * [x] deleteDatabaseHandler() 741ae22d5b1f87538d3baf802152bda8b00f7af1
    * [x] deleteTagHandler() e138056c1b82f08ef9e84bb2cbd51625de7f9d2d
    * [x] markdownPreview() 695171c5540a2a1be54dc44a554e700e1e9c15a7
    * [x] prefHandler()
    * [x] saveSettingsHandler() 2531faee7dc0c9564f904e01be25a6e4d25cdbb4
    * [x] setDefaultBranchHandler() fa1f0e17b3390b2c3658d794bd7030e8a707988a
    * [x] tableViewHandler()
    * [x] tagsPage()
    * [x] updateBranchHandler() 0a5a0f4420beaa13c49aeb6eedf1ac0901b56614
    * [x] updateTagHandler() 18b75468db6b9a0c56af1ca85c387e32655d0d48
    * [x] uploadDataHandler() fe3b8c36d4d90986211ffb15a97b957029e0a5a2
* [x] Put the new webUI server online
  * Probably need to blow away the old dev1 server (eg don't reuse it).
  * [x] Email our dev mailing list once it's done, for initial testing
* [x] Add a working Releases page 187b232d92184feb15f5790a5215f7a59b8b0b37
* [x] Fix the bug whereby when a tag is deleted, the old tag count is shown to logged out/anonymous users. 4372057b8fdb7ecb688377da8e85dd4028d02a09
* [x] Add obvious Download button to the Releases page f56e24e9d766d812ecd77a0d4f3e122c18201a45
* [x] Setup http → https redirect for db4s-beta server #59
* [x] Fix the "empty root dir when user has no databases" bug #58 3134ce14f3d22ea5470028e2d94ae475bfbe3f8d
* [x] Add database delete confirmation page #57 4a93997254421a60d271b99843ac923f5d2538ed
* [x] Add download size info to the releases page ca3e9cd863a027aad84d7cd4aa9561edfaa7b863
* [x] Look into why the initial commit message for the DB4S Download stats db was a copy of the project description
  * Seems like a case of my putting the project description into the commit message field when first uploading.  I'm calling it "not enough sleep". :wink:
  * Recreated the database without the incorrect initial commit message.
* [x] <strike>Look into why DB4S on OSX isn't connecting to the db4s-beta server
  * The old Qt .validate() problem?</strike>
  * Seems to be working now.  Possibly related to my forgetting to initially configure the DB4S end point server name in the .dbhub/config.toml file on the server.
* [ ] Look into the error with creation of users from GitHub which Martin mentioned. - \***in progress**\*
  * Looking at the db4s-beta logs, other people may be experiencing the same thing and not reporting it.
  * 5be3bdb28993a8360a5daac74bede51a7b0ca06e should fix this.
  * Emailed @MKleusberg to try it out. :smile:
* [x] Add horizontal scrollbars for very wide tables, as per #35 a69ad911e834c8a970230fac0745c1afa9af395c

## DB4S

* [ ] Find out if the latest SQLCipher is affected by the recent SQLite CVE's - \***in progress**\*
  * [x] Point the SQLCipher team at the recent SQLite CVE's, and the recent DefCon presentation on SQLite.  Emailed Zetetic on 30th July.

**Comment by justinclift** [comment]
Stuff not completed has been moved to #62
