### ISSUE TITLE
To Do list for 14th - 18th August

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#79]
## DBHub.io

* [ ] Implement fixes for the pieces @chrisjlocke pointed out
  * [x] Show timestamps in the users' browser time, not hard coded to UTC #77 9fdb564f0b1fb8122d71e878d69df2ebc18f65b8
  * [x] Add a cog icon to database entries on the profile page, for easily getting to the database settings #78 c5ce853cd24b3e1adb9e0f046b3d831e2ed98992
  * [x] Fix the text in drop down menus having an I beam, not an arrow #71 7f85ce8d8e7f36c7576304b345771abdddaf4ada
  * [x] The leading slash in breadcrumb trails should go to user home page
    * Removed the leading slash instead, as it seems redundant now we have a front page 22476db97895eb3d0ccc8c36315cc287d10cd1a0
  * [x] The links to "CommonMark" in various "Markdown is supported" places should open in a new window #71 2b4e40c3887902bf5eaaca53fe71a41cd24017da
  * [x] Downloaded file names have `+` signs instead of spaces in their names #71 37b2e668bc5a68cef4ed833e3fdc15d7b3c13bac
  * [x] Look into why pushing a database that has a `+` sign in the name fails #76 bc51437515bcafeb29e11614ce110904e989bc54
  * [x] When the user is first setting up their full name and email address, if they haven't supplied an email then pre-fill it with the same one suggested for privacy #71 d189beb2286781f4a9e9a3c9a824e450a9ac4ba4
  * [x] When typing in the description, etc, newlines don't seem to be working properly #71
  * Implemented this by using a different markdown renderer, and customising it to use our preferred settings (as it doesn't accept options itself). ebd352356346cae84bec332576516dc09d670b97
  * [x] Condense the list of databases in the profile and user pages #77 d21e54951a847feaa19e2b15048651f47f0d3335
    * Not sure if the fields shown for the collapsed state on the user page are the right choice.  Guessing they'll need adjusting, which is very easy to do.
  * [ ] Pushing a database with multi-line commit message results in an error #75
    * After initial investigation, it seems like the PUT request is being malformed by DB4S
    * Switched the DB4S end point to use POST requests and multi-part form data.  That should let us solve this problem in a more robust way. 012cc22c952ebdc2fa8dab39b66cb4a77fade059
    * In theory this is fixed now.  Asked @chrisjlocke to verify it when he has a chance
* [x] Edit/Preview headings for markdown preview are still blue.  Change to black for consistency. 4d03df3e9829670c44652ca295b481467ec1d830
* [x] "blackLink" css class seems a bit too dark.  Lighten it a bit. 9cb930a9ddde02ad52a9482873f9f2c7e39baf17
* [x] With very wide tables the pagination arrows aren't well placed cd15305fa27c891d45cf4e26c9172c80067fca5d
* [x] Database view statistics are lost whenever memcached is restarted 8338b9857423f21dedd469b1187a61a3a3fd3f5a
  * Silly bug.  The view counts were being flushed to database ok, but never being read back.
* [x] Ensure uploads through DB4S honour maximum size limit 320e163d9aaa23253e095d5ee4c72e7b951aa98e
  * Maximum database upload size for now is 100MB.  Hopefully a reasonable starting point.
* [x] Add users display names to the stars page.  Make the link text black too 5b71f4c0f461e8f13a98b9e6ec4453e1c2eec23d
* [x] Add better logging of all uploads and downloads 44f514e96a61c3a37fca86dca5e3141b702dcdcf 42fa307770171a1f8cca4c74f61dc6f9b4bd273b
* [x] Make an automatic bounce from dbhub.io to the db4s-beta site (for now anyway)
  * Now in place.  Hopefully not too premature. :wink:
* [ ] Create the front page
  * [x] For the Stars and Forks stats, their counters should probably take people to the matching Stars and Forks page 4ded8efe0c9c874e5ec3bcb5344fd387dd74a2ef

## DB4S

* [x] Create screenshots for the Chinese translation https://github.com/sqlitebrowser/sqlitebrowser/pull/1085
* [x] Update the SQLCipher build in my repo with the latest SQLCipher + the upstream CVE patch
  * This will make for a safe, CVE free version we can build our Windows binaries with
* [x] Add the upstream patch for CVE-2017-10989 to Homebrew
  * https://github.com/Homebrew/homebrew-core/pull/16961
* [x] Release DB4S 3.10.0
  * https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.0

**Comment by justinclift** [comment]
Incomplete stuff moved to #89
