### ISSUE TITLE
To Do list for 28th August - 1st September

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/dbhub.io#90]
## DBHub.io

* [x] Add useful basic functionality to the initial discussion system
  * [x] Edit existing comment, for db owner and comment creator
    * [x] Editing discussion title f03ad124ba9e43611566a8333f3451cb5841f274
    * [x] Editing comment text 35f448cccc80253af52ce475f9aabd8ddd8dc3d1
* [x] Look into the recent run of `SELECT * FROM "" LIMIT 10 OFFSET 0` messages on the db4s-beta system console 0c13e885786a372c5c9eca10d5695ab1d217270f
* [x] Ensure line breaks in text fields are honoured 9e77cd6f61a3ffd10ba830be54b8bad740c65bc7
  * Used `<pre>` tags for displaying database fields and applying appropriate style so they look ok.
  * Apparently using `style="white-space:pre-wrap;"` on `div`'s and similar works, though I haven't yet tried that.
    * This seems like good info: https://stackoverflow.com/questions/19684708/preserve-line-breaks-in-angularjs.
    * https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
* [x] Look into that `memcache: cache miss` error #95 9dcc844c2bde028a8a4e578d4d9c526a1ac39010
* [x] Return commit ID for uploads from DB4S efd2a6ca4bab0f2c61547be64e65ccf516c4b306
* [x] Add branch querying end point for DB4S https://github.com/sqlitebrowser/dbhub.io/issues/99#issuecomment-326650539 b71b335503b984a79424f5977993973f1d640b06
* [x] Update pages to use rounded corners a142f04553d923e7c373362140745378019d3d97 cd0539eb3b83b532cb738df078d69bad1fbea043 cf79fb7f2e421ec29065d0551d2b7f8aa28ee592 f4d40631ca75e02d2ca367e751c220a1de6d76f1
* [ ] When people download a database or CSV file, send them the compressed (.zip) version
  * Or at least add an option to the download button dropdown, making it a chooseable option
* [ ] Add forking and collision detection for uploads from DB4S #99 - **\* in progress \*** 
* [ ] Try out the date display javascript function @chrisjlocke emailed
* [ ] Look into why the `<//////b>` isn't showing up in the comment edit window
  * https://db4s-beta.dbhub.io/discuss/justinclift/DB4S%20download%20stats.sqlite?id=6
* [ ] Find out why DB4S uploaded databases weren't invalidating memcache entries
* [ ] Finish the "Expanded SQL" PR for https://github.com/gwenn/gosqlite/issues/10#issuecomment-297830554
  * Initial PR fails on Travis: https://github.com/gwenn/gosqlite/pull/11
* [ ] Create some kind of launcher for the webUI on FreeBSD, so Golang crashes don't cause an outage
* [ ] Initial implementation of Merge Requests
* [ ] Initial implementation of watchers
* [ ] Look into what it would take to display gravatars and/or auth provider supplied images
* [ ] Add a "Create new branch" button to the branches page #71
* [ ] Add a "Create new tag" button to the tags page #71
* [ ] Add a "Create new release" button to the releases page #71 
* [ ] Initial CSV upload implementation.  As per #28.
* [ ] Create the front page
  * [ ] Data sets for exploring
  * [ ] Header bar
    * [ ] Features
    * [ ] Videos
    * [ ] Docs
    * [ ] API
* [ ] Delete releases needs an 'are you sure?' #71
* [ ] Add sorting options to the database lists on the profile and user pages #77
  * Sort by name and sort by last modified
  * Drop down selector maybe?
* [ ] Figure out a good way to guide users in creating a new commit, as it's not immediately obvious atm #71
* [ ] Add auto-restart for the webUI launch process so Golang crashes don't kill the site #73
* [ ] Add a bunch of example databases to the new db4s-beta server
  * Some [NICVA](https://data.gov.uk) [databases added](https://db4s-beta.dbhub.io/nicva).
  * There was a bug in Auth0 stopping the upload of databases from [data.gov.uk](https://data.gov.uk).
    * Bug # 26204 filed with Auth0.
    * Fixed in the new [v10.20.0](https://github.com/auth0/lock/releases/tag/v10.20.0) release of lock.
* [ ] Run `EXPLAIN ANALYZE` on all of our queries in postgresql.go, making sure the indices and similar are reasonable
* [ ] Make sure all stored data structures are as expected (eg commit->tree->entries, and commit sha256 structure internals), just to be on the safe side
  * Make sure the general structure is ok
  * It might also be useful to create a quick and dirty CLI tool which reads + validates the json structures in database entries (in bulk)
* [ ] Significant quantity of testing :smile:
* [ ] Allow Auth0 database users to change their password, as per #44
* [ ] Add further DB4S end point pieces
  * Much of this stuff probably won't be used right away, but having it in place gives us options to enhance the Remote tab in DB4S as time/interest permits
  * [ ] Query for user info
    * [ ] Full name
    * [ ] Date joined
    * [ ] Gravatar image?
  * [ ] Delete remote database
  * [ ] Delete latest commit (for a branch), tag, release, branch
  * [ ] Create/update tag, branch, release  
* [ ] The headings on the front page ("Most downloaded" etc) should be clickable, and go to a full page showing many results (top 250 or something maybe?)
* [ ] API server and `dio`
  * We'll need to figure out the authentication approach for the API server and `dio` too
    * Certs or API key?  API key is probably lowest overhead, as certs would add kB's and latency to every request
    * On the other hand, unless we're planning on supporting plain http we're going to be using certs to some extent anyway.  And DB4S **requires** the use of client side certs.
    * Looking around online (quickly), it seems like HTTPS-only is the direction for API's these days.  So, the session overhead of HTTPS is probably "just how it is" these days.
      * Example reference info (there are likely better sources): https://https.cio.gov/apis

## DB4S

* [ ] Test out [Hugo](https://github.com/spf13/hugo) as a potential blog platform (aka sqlitebrowser.org/blog)
* [ ] Testing DB4S fixes
  * [ ] https://github.com/sqlitebrowser/sqlitebrowser/issues/583
* [ ] File issues on the upstream projects causing the DB4S compilation warnings https://github.com/sqlitebrowser/sqlitebrowser/issues/1042#issuecomment-311657316
* [ ] Update the DB4S installation docs for Linux
  * [ ] Debian/Ubuntu
  * Related:
    * https://github.com/sqlitebrowser/sqlitebrowser/issues/832#issuecomment-271159422
    * https://github.com/sqlitebrowser/sqlitebrowser/issues/994

**Comment by justinclift** [comment]
Incomplete tasks moved to #102.
